### ISSUE TITLE
Does not function in modern versions of Blender

### ISSUE THREAD

**Issue by YaBoiRoy** [AsteriskAmpersand/Monster-Hunter-Frontier-Importer#2]
You need to edit __init__.py for the plugin to appear as an option in the first place, adding a blender version tag. After this is done, it spits out an error:
![image](https://user-images.githubusercontent.com/34889422/113552965-95876200-95bc-11eb-8293-a70bd5c4ae08.png)

**Comment by AsteriskAmpersand** [comment]
Yes, you need blender 2.79. Plugin will never be updated for more modern versions.

**Comment by YaBoiRoy** [comment]
Fair, I downloaded it immediately after submitting the issue anyway. Thanks for the plugin!
