### ISSUE TITLE
imported .fskl are empty axis and not bones

### ISSUE THREAD

**Issue by blagapar** [AsteriskAmpersand/Monster-Hunter-Frontier-Importer#4]
Thank you for this plugin, it works great except when I import an armature, bones are all empty axis, and so I can't set to parent and animate. Is it normal ? 

Thanks

**Comment by AsteriskAmpersand** [comment]
Yes. MH uses joints not bones, so for things to be correctly represented in blender it must be as a hierarchy of empties.
