### ISSUE TITLE
Sorry, I am unable to use it

### ISSUE THREAD

**Issue by 1246adm** [AsteriskAmpersand/Monster-Hunter-Frontier-Importer#5]
May I ask which version of Blender is required to use this plugin? I have tried 2.8, 2.9, and 3.1, the plugin is installed normally but cannot be used

**Comment by Houmgaor** [comment]
Try Blender 2.79. You need [this line](https://github.com/Houmgaor/Monster-Hunter-Frontier-Importer/blob/525520e72739387c1dfa0e74660c893c1d7a9b47/__init__.py#L24) in bl_info to have the add-on running, but you will need additional code updates I have included in my fork (works with Blender 2.91).

**Comment by AsteriskAmpersand** [comment]
2.79b is the intended version.
